version: '3.8'

services:
  
  mysql-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    env_file:
      - .env
    command:
      - --authentication_policy=mysql_native_password 
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
    restart: always

  web:
    build:
      context: .
    
    command: > 
      sh -c "
            python3 manage.py makemigrations &&
            python3 manage.py migrate && 
            python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
      - ./media:/media
    env_file:
      - .env
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    links:
      - "mysql-db:mysql-db"
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mysql-db
    ports:
      - "70:80"