version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: teachteam-mysql-db
    ports:
      - "3307:3306"
    env_file:
      - .env
    command:
      - --authentication_policy=mysql_native_password 
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'


  todo_app:
    build:
      context: .
    
    command: > 
      sh -c "
            python3 manage.py makemigrations &&
            python3 manage.py migrate && 
            python3 manage.py runserver 0.0.0.0:8000"
    container_name: todo_app
    volumes:
      - ./:/app
      - ./media:/media
    env_file:
      - .env
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - mysql-db
    ports:
      - 8000:8000
      - 3000:3000

