version: '3.8'

services:
  
  mysql-db:
    image: mysql:latest
    container_name: teachteam-mysql-db
    ports:
      - "3307:3306"
    env_file:
      - .env
    command:
      - --authentication_policy=mysql_native_password 
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network

  web:
    build:
      context: .
    
    command: > 
      sh -c "
            python3 manage.py makemigrations &&
            python3 manage.py migrate && 
            python3 manage.py runserver 0.0.0.0:7070"
    restart: always
    volumes:
      - ./:/app
      - ./media:/media
    env_file:
      - .env
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    
    deploy:
      replicas: 3
    
    depends_on:
      - mysql-db
    networks:
      - app-network
    ports:
      - 7070:7070

networks:
  app-network:
    driver: bridge