# Generated by Django 3.1.6 on 2021-02-27 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='regisDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Regis Date'),
        ),
    ]
